"""
DET Flow - Database Models
Defines SQLAlchemy ORM models for users, submissions, and scores.
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, JSON, Boolean, Text, Numeric
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from datetime import datetime

from core.database import Base


class User(Base):
    """
    User model representing DET students.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    phone_number = Column(String(20), unique=True, index=True, nullable=False)
    name = Column(String(255), nullable=True)
    email = Column(String(255), unique=True, nullable=True)

    # Profile information
    target_score = Column(Integer, nullable=True)
    current_level = Column(String(10), nullable=True)  # A1, A2, B1, B2, C1, C2

    # Tracking
    total_submissions = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    last_active = Column(DateTime(timezone=True), nullable=True)

    # Status
    is_active = Column(Boolean, default=True)
    subscription_tier = Column(String(50), default="free")  # free, premium, pro

    # Relationships
    submissions = relationship("Submission", back_populates="user", cascade="all, delete-orphan")
    sessions = relationship("UserSession", back_populates="user", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<User(id={self.id}, phone={self.phone_number}, name={self.name})>"


class Submission(Base):
    """
    Submission model representing student answers to DET tasks.
    """
    __tablename__ = "submissions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    # Task information
    task_type = Column(String(50), nullable=False)  # read_aloud, describe_image, write_about_photo, etc.
    task_prompt = Column(Text, nullable=True)

    # Student response
    response_text = Column(Text, nullable=True)
    response_audio_url = Column(String(512), nullable=True)
    response_image_url = Column(String(512), nullable=True)

    # Evaluation results
    overall_score = Column(Integer, nullable=True)  # 10-160 scale

    # Subscores (each 10-160)
    literacy_score = Column(Integer, nullable=True)
    comprehension_score = Column(Integer, nullable=True)
    conversation_score = Column(Integer, nullable=True)
    production_score = Column(Integer, nullable=True)

    # Detailed feedback
    feedback = Column(JSON, nullable=True)  # Stores detailed evaluation as JSON
    evaluator_comments = Column(Text, nullable=True)

    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    evaluated_at = Column(DateTime(timezone=True), nullable=True)
    evaluation_duration_ms = Column(Integer, nullable=True)

    # Status
    status = Column(String(20), default="pending")  # pending, evaluating, completed, failed

    # Relationships
    user = relationship("User", back_populates="submissions")

    def __repr__(self):
        return f"<Submission(id={self.id}, user_id={self.user_id}, task={self.task_type}, score={self.overall_score})>"


class UserSession(Base):
    """
    User session tracking for conversation continuity.
    """
    __tablename__ = "user_sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    # Session data
    session_id = Column(String(255), unique=True, index=True, nullable=False)
    context = Column(JSON, nullable=True)  # Stores conversation context

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_interaction = Column(DateTime(timezone=True), server_default=func.now())
    expires_at = Column(DateTime(timezone=True), nullable=True)

    # Status
    is_active = Column(Boolean, default=True)

    # Relationships
    user = relationship("User", back_populates="sessions")

    def __repr__(self):
        return f"<UserSession(id={self.id}, session_id={self.session_id}, user_id={self.user_id})>"


class StudyPlan(Base):
    """
    Personalized study plans generated by the Pedagogue Agent.
    """
    __tablename__ = "study_plans"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    # Plan details
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    plan_data = Column(JSON, nullable=False)  # Detailed plan structure

    # Duration
    start_date = Column(DateTime(timezone=True), nullable=True)
    end_date = Column(DateTime(timezone=True), nullable=True)
    duration_weeks = Column(Integer, nullable=True)

    # Progress tracking
    completion_percentage = Column(Float, default=0.0)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Status
    is_active = Column(Boolean, default=True)

    def __repr__(self):
        return f"<StudyPlan(id={self.id}, user_id={self.user_id}, title={self.title})>"


class Payment(Base):
    """
    Payment model representing subscription payment transactions.
    """
    __tablename__ = "payments"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    # Payment provider details
    payment_id = Column(String(255), unique=True, index=True)  # External provider ID
    provider = Column(String(50), default="mercadopago")  # mercadopago, stripe, manual

    # Amount and currency
    amount = Column(Numeric(10, 2), nullable=False)
    currency = Column(String(3), default="BRL")

    # Subscription details
    subscription_plan = Column(String(20), nullable=False)  # weekly, monthly, yearly

    # Status
    status = Column(String(30), default="pending")  # pending, approved, rejected, etc.
    status_detail = Column(String(100), nullable=True)

    # Payment method
    payment_method = Column(String(50), nullable=True)  # pix, credit_card, etc.
    payment_method_id = Column(String(100), nullable=True)

    # PIX specific fields
    pix_qr_code = Column(Text, nullable=True)
    pix_qr_code_base64 = Column(Text, nullable=True)
    pix_expiration_date = Column(DateTime(timezone=True), nullable=True)

    # Metadata
    external_reference = Column(String(255), nullable=True)
    description = Column(Text, nullable=True)
    metadata_json = Column("metadata", JSON, nullable=True)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    approved_at = Column(DateTime(timezone=True), nullable=True)
    expires_at = Column(DateTime(timezone=True), nullable=True)

    # Receipt and invoice
    receipt_url = Column(String(512), nullable=True)
    invoice_id = Column(String(255), nullable=True)

    # Relationship
    user = relationship("User")

    def __repr__(self):
        return f"<Payment(id={self.id}, user_id={self.user_id}, amount={self.amount}, status={self.status})>"


class SubscriptionHistory(Base):
    """
    Subscription history tracking changes over time.
    """
    __tablename__ = "subscription_history"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    # Subscription details
    plan = Column(String(20), nullable=False)
    status = Column(String(20), nullable=False)

    # Dates
    start_date = Column(DateTime(timezone=True), nullable=False)
    end_date = Column(DateTime(timezone=True), nullable=True)

    # Change reason
    action = Column(String(50), nullable=False)  # created, renewed, cancelled, etc.
    reason = Column(Text, nullable=True)

    # Payment reference
    payment_id = Column(Integer, ForeignKey("payments.id"), nullable=True)

    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    metadata_json = Column("metadata", JSON, nullable=True)

    # Relationships
    user = relationship("User")
    payment = relationship("Payment")

    def __repr__(self):
        return f"<SubscriptionHistory(id={self.id}, user_id={self.user_id}, action={self.action})>"
